title: "[Idea] "
labels:
  - idea
body:
  - type: markdown
    attributes:
      value: |
        Thanks for sharing your idea! We love hearing from the community.

  - type: textarea
    id: idea
    attributes:
      label: What's your idea?
      description: Describe your feature idea or suggestion
      placeholder: "I think it would be great if..."
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: How would you use this feature? What problem does it solve?
      placeholder: "This would help me when..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives or workarounds
      description: Have you tried any workarounds? Are there alternative approaches?
      placeholder: "Currently I'm doing X, but it would be better if..."
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Would you like to contribute?
      options:
        - label: I'd be willing to help implement this feature
        - label: I'd be willing to help test this feature
        - label: I'd be willing to help document this feature
