import {
  PhoneCall,
  Clock,
  Phone,
  Calendar,
  Copy,
  CheckCircle2,
} from "lucide-react";
import { useState } from "react";

interface CallbackScheduledCardProps {
  date: string;
  time: string;
  phone: string;
  customerName?: string;
}

// Generate ICS file content for calendar event
function generateICSFile(
  title: string,
  description: string,
  date: string,
  time: string,
  durationMinutes: number = 30,
): string {
  // Parse date and time to create proper datetime
  // Expected formats: date="Jan 15, 2025" or "2025-01-15", time="2:30 PM" or "14:30"
  const eventDate = new Date(`${date} ${time}`);

  // If parsing fails, use tomorrow at the specified time
  if (isNaN(eventDate.getTime())) {
    const tomorrow = new Date();
    tomorrow.setDate(tomorrow.getDate() + 1);
    tomorrow.setHours(14, 30, 0, 0); // Default to 2:30 PM
    eventDate.setTime(tomorrow.getTime());
  }

  const endDate = new Date(eventDate.getTime() + durationMinutes * 60 * 1000);

  // Format dates for ICS (YYYYMMDDTHHmmss format)
  const formatICSDate = (d: Date): string => {
    return d.toISOString().replace(/[-:]/g, "").split(".")[0] + "Z";
  };

  const now = new Date();
  const uid = `callback-${now.getTime()}@copilot-sdk`;

  return `BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Copilot SDK//Callback Scheduler//EN
CALSCALE:GREGORIAN
METHOD:PUBLISH
BEGIN:VEVENT
UID:${uid}
DTSTAMP:${formatICSDate(now)}
DTSTART:${formatICSDate(eventDate)}
DTEND:${formatICSDate(endDate)}
SUMMARY:${title}
DESCRIPTION:${description.replace(/\n/g, "\\n")}
STATUS:CONFIRMED
END:VEVENT
END:VCALENDAR`;
}

// Download ICS file - triggers native calendar app on Mac/Windows/Linux
function downloadICSFile(content: string, filename: string): void {
  const blob = new Blob([content], { type: "text/calendar;charset=utf-8" });
  const url = URL.createObjectURL(blob);

  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  URL.revokeObjectURL(url);
}

export function CallbackScheduledCard({
  date,
  time,
  phone,
  customerName = "Customer",
}: CallbackScheduledCardProps) {
  const [copied, setCopied] = useState(false);
  const [addedToCalendar, setAddedToCalendar] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(
      `Callback: ${date} at ${time}\nPhone: ${phone}`,
    );
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleAddToCalendar = () => {
    const title = `Callback: ${customerName}`;
    const description = `Scheduled callback with ${customerName}\nPhone: ${phone}\n\nGenerated by Copilot SDK`;

    const icsContent = generateICSFile(title, description, date, time, 30);
    downloadICSFile(
      icsContent,
      `callback-${date.replace(/[^a-zA-Z0-9]/g, "-")}.ics`,
    );

    setAddedToCalendar(true);
  };

  return (
    <div className="bg-card border border-border rounded-xl p-4 space-y-3">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <PhoneCall className="w-5 h-5 text-primary" />
          <span className="text-sm font-semibold text-foreground">
            Callback Scheduled
          </span>
        </div>
        {addedToCalendar && (
          <span className="text-xs text-green-600 flex items-center gap-1">
            <CheckCircle2 className="w-3 h-3" /> Added
          </span>
        )}
      </div>
      <div className="text-sm space-y-2">
        <div className="flex items-center gap-2">
          <Clock className="w-4 h-4 text-muted-foreground" />
          <span className="text-foreground">
            {date} at {time}
          </span>
        </div>
        <div className="flex items-center gap-2">
          <Phone className="w-4 h-4 text-muted-foreground" />
          <span className="text-foreground">{phone}</span>
        </div>
      </div>
      <div className="flex gap-2 pt-2">
        <button
          onClick={handleAddToCalendar}
          disabled={addedToCalendar}
          className="flex-1 flex items-center justify-center gap-2 px-3 py-2 bg-primary text-primary-foreground rounded-lg hover:bg-primary/90 transition-colors text-sm font-medium disabled:opacity-50"
        >
          <Calendar className="w-4 h-4" />
          {addedToCalendar ? "Added to Calendar" : "Add to Calendar"}
        </button>
        <button
          onClick={handleCopy}
          className="px-3 py-2 border border-border text-foreground rounded-lg hover:bg-accent transition-colors text-sm"
        >
          {copied ? (
            <CheckCircle2 className="w-4 h-4 text-green-500" />
          ) : (
            <Copy className="w-4 h-4" />
          )}
        </button>
      </div>
    </div>
  );
}
