import {
  PhoneCall,
  Clock,
  Phone,
  Calendar,
  Copy,
  CheckCircle2,
  X,
  User,
} from "lucide-react";
import { useState } from "react";

interface TimeSlot {
  date: string;
  time: string;
  displayDate: string;
  available: boolean;
}

interface CallbackScheduledCardProps {
  /** Mode: "select" for approval-required, "confirmed" for completed */
  mode?: "select" | "confirmed";
  date?: string;
  time?: string;
  phone: string;
  customerName?: string;
  /** Called when user selects a time slot (select mode) */
  onSelectSlot?: (slot: TimeSlot) => void;
  /** Called when user cancels (select mode) */
  onCancel?: () => void;
}

// Generate available time slots for the next few days
function generateTimeSlots(): TimeSlot[] {
  const slots: TimeSlot[] = [];
  const now = new Date();

  // Generate slots for the next 3 days
  for (let dayOffset = 0; dayOffset < 3; dayOffset++) {
    const date = new Date(now);
    date.setDate(date.getDate() + dayOffset);

    const dayName =
      dayOffset === 0
        ? "Today"
        : dayOffset === 1
          ? "Tomorrow"
          : date.toLocaleDateString("en-US", { weekday: "long" });

    const displayDate = `${dayName}, ${date.toLocaleDateString("en-US", { month: "short", day: "numeric" })}`;
    const dateStr = date.toISOString().split("T")[0];

    // Morning and afternoon slots
    const times = ["9:00 AM", "10:30 AM", "2:00 PM", "3:30 PM", "5:00 PM"];

    for (const time of times) {
      // Randomly mark some as unavailable for realism
      const available = Math.random() > 0.3;
      slots.push({
        date: dateStr,
        time,
        displayDate,
        available,
      });
    }
  }

  return slots;
}

// Generate ICS file content for calendar event
function generateICSFile(
  title: string,
  description: string,
  date: string,
  time: string,
  durationMinutes: number = 30,
): string {
  const eventDate = new Date(`${date} ${time}`);

  if (isNaN(eventDate.getTime())) {
    const tomorrow = new Date();
    tomorrow.setDate(tomorrow.getDate() + 1);
    tomorrow.setHours(14, 30, 0, 0);
    eventDate.setTime(tomorrow.getTime());
  }

  const endDate = new Date(eventDate.getTime() + durationMinutes * 60 * 1000);

  const formatICSDate = (d: Date): string => {
    return d.toISOString().replace(/[-:]/g, "").split(".")[0] + "Z";
  };

  const now = new Date();
  const uid = `callback-${now.getTime()}@copilot-sdk`;

  return `BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Copilot SDK//Callback Scheduler//EN
CALSCALE:GREGORIAN
METHOD:PUBLISH
BEGIN:VEVENT
UID:${uid}
DTSTAMP:${formatICSDate(now)}
DTSTART:${formatICSDate(eventDate)}
DTEND:${formatICSDate(endDate)}
SUMMARY:${title}
DESCRIPTION:${description.replace(/\n/g, "\\n")}
STATUS:CONFIRMED
END:VEVENT
END:VCALENDAR`;
}

function downloadICSFile(content: string, filename: string): void {
  const blob = new Blob([content], { type: "text/calendar;charset=utf-8" });
  const url = URL.createObjectURL(blob);

  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  URL.revokeObjectURL(url);
}

export function CallbackScheduledCard({
  mode,
  date,
  time,
  phone,
  customerName = "Customer",
  onSelectSlot,
  onCancel,
}: CallbackScheduledCardProps) {
  const [copied, setCopied] = useState(false);
  const [addedToCalendar, setAddedToCalendar] = useState(false);
  const [selectedDay, setSelectedDay] = useState(0);
  const [slots] = useState(() => generateTimeSlots());

  // Group slots by day
  const slotsByDay = slots.reduce(
    (acc, slot) => {
      if (!acc[slot.displayDate]) {
        acc[slot.displayDate] = [];
      }
      acc[slot.displayDate].push(slot);
      return acc;
    },
    {} as Record<string, TimeSlot[]>,
  );

  const days = Object.keys(slotsByDay);

  const handleCopy = () => {
    navigator.clipboard.writeText(
      `Callback: ${date} at ${time}\nPhone: ${phone}`,
    );
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleAddToCalendar = () => {
    const title = `Callback: ${customerName}`;
    const description = `Scheduled callback with ${customerName}\nPhone: ${phone}\n\nGenerated by Copilot SDK`;

    const icsContent = generateICSFile(title, description, date!, time!, 30);
    downloadICSFile(
      icsContent,
      `callback-${date!.replace(/[^a-zA-Z0-9]/g, "-")}.ics`,
    );

    setAddedToCalendar(true);
  };

  // Selection mode (approval-required state)
  if (mode === "select") {
    return (
      <div className="bg-card border border-yellow-500/30 rounded-xl p-4 space-y-3">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Calendar className="w-5 h-5 text-yellow-500" />
            <span className="text-sm font-semibold text-foreground">
              Schedule Callback
            </span>
          </div>
        </div>

        <div className="flex items-center gap-2 p-2 bg-muted rounded-lg">
          <User className="w-4 h-4 text-muted-foreground" />
          <span className="text-sm text-foreground">{customerName}</span>
          <span className="text-xs text-muted-foreground ml-auto">{phone}</span>
        </div>

        {/* Day selector tabs */}
        <div className="flex gap-1 border-b border-border">
          {days.map((day, i) => (
            <button
              key={day}
              onClick={() => setSelectedDay(i)}
              className={`px-3 py-2 text-xs font-medium transition-colors ${
                selectedDay === i
                  ? "text-primary border-b-2 border-primary -mb-px"
                  : "text-muted-foreground hover:text-foreground"
              }`}
            >
              {day.split(",")[0]}
            </button>
          ))}
        </div>

        {/* Time slots for selected day */}
        <div className="space-y-2">
          <span className="text-xs text-muted-foreground">
            {days[selectedDay]}
          </span>
          <div className="grid grid-cols-3 gap-2">
            {slotsByDay[days[selectedDay]]?.map((slot, i) => (
              <button
                key={i}
                onClick={() => slot.available && onSelectSlot?.(slot)}
                disabled={!slot.available}
                className={`px-3 py-2 text-xs rounded-lg transition-all ${
                  slot.available
                    ? "bg-muted hover:bg-primary hover:text-primary-foreground font-medium"
                    : "bg-muted/50 text-muted-foreground/50 cursor-not-allowed line-through"
                }`}
              >
                {slot.time}
              </button>
            ))}
          </div>
        </div>

        <div className="pt-2 border-t border-border">
          <button
            onClick={onCancel}
            className="flex items-center justify-center gap-1.5 px-3 py-2 text-xs text-muted-foreground hover:text-foreground transition-colors w-full"
          >
            <X className="w-3 h-3" />
            Cancel
          </button>
        </div>
      </div>
    );
  }

  // Confirmed mode (completed state) - default behavior
  return (
    <div className="bg-card border border-green-500/30 rounded-xl p-4 space-y-3">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <CheckCircle2 className="w-5 h-5 text-green-500" />
          <span className="text-sm font-semibold text-green-600">
            Callback Scheduled
          </span>
        </div>
        {addedToCalendar && (
          <span className="text-xs text-green-600 flex items-center gap-1">
            <CheckCircle2 className="w-3 h-3" /> Added
          </span>
        )}
      </div>

      <div className="p-3 bg-green-500/5 rounded-lg border border-green-500/20">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-full bg-green-500/20 text-green-600 flex items-center justify-center">
            <PhoneCall className="w-5 h-5" />
          </div>
          <div className="flex-1">
            <div className="text-sm font-medium text-foreground">
              {customerName}
            </div>
            <div className="flex items-center gap-3 text-xs text-muted-foreground mt-0.5">
              <span className="flex items-center gap-1">
                <Clock className="w-3 h-3" />
                {date} at {time}
              </span>
              <span className="flex items-center gap-1">
                <Phone className="w-3 h-3" />
                {phone}
              </span>
            </div>
          </div>
        </div>
      </div>

      <div className="flex gap-2 pt-2">
        <button
          onClick={handleAddToCalendar}
          disabled={addedToCalendar}
          className="flex-1 flex items-center justify-center gap-2 px-3 py-2 bg-primary text-primary-foreground rounded-lg hover:bg-primary/90 transition-colors text-sm font-medium disabled:opacity-50"
        >
          <Calendar className="w-4 h-4" />
          {addedToCalendar ? "Added to Calendar" : "Add to Calendar"}
        </button>
        <button
          onClick={handleCopy}
          className="px-3 py-2 border border-border text-foreground rounded-lg hover:bg-accent transition-colors text-sm"
        >
          {copied ? (
            <CheckCircle2 className="w-4 h-4 text-green-500" />
          ) : (
            <Copy className="w-4 h-4" />
          )}
        </button>
      </div>
    </div>
  );
}
