export type TransactionCategory =
  | "groceries"
  | "dining"
  | "transport"
  | "utilities"
  | "entertainment"
  | "shopping"
  | "healthcare"
  | "income"
  | "transfer";

export interface Transaction {
  id: string;
  accountId: string;
  date: string;
  description: string;
  merchant: string;
  category: TransactionCategory;
  amount: number;
  type: "debit" | "credit" | "transfer";
  status: "completed" | "pending" | "failed";
}

export const categoryColors: Record<TransactionCategory, string> = {
  groceries: "#22c55e",
  dining: "#f97316",
  transport: "#3b82f6",
  utilities: "#8b5cf6",
  entertainment: "#ec4899",
  shopping: "#eab308",
  healthcare: "#14b8a6",
  income: "#00ba7c",
  transfer: "#64748b",
};

export const categoryLabels: Record<TransactionCategory, string> = {
  groceries: "Groceries",
  dining: "Dining",
  transport: "Transport",
  utilities: "Utilities",
  entertainment: "Entertainment",
  shopping: "Shopping",
  healthcare: "Healthcare",
  income: "Income",
  transfer: "Transfer",
};

export const transactions: Transaction[] = [
  {
    id: "txn-001",
    accountId: "acc-001",
    date: "2025-01-28",
    description: "Weekly grocery shopping",
    merchant: "Whole Foods Market",
    category: "groceries",
    amount: -156.78,
    type: "debit",
    status: "completed",
  },
  {
    id: "txn-002",
    accountId: "acc-001",
    date: "2025-01-28",
    description: "Monthly salary deposit",
    merchant: "Acme Corp",
    category: "income",
    amount: 8500.0,
    type: "credit",
    status: "completed",
  },
  {
    id: "txn-003",
    accountId: "acc-001",
    date: "2025-01-27",
    description: "Dinner with friends",
    merchant: "The Italian Kitchen",
    category: "dining",
    amount: -87.45,
    type: "debit",
    status: "completed",
  },
  {
    id: "txn-004",
    accountId: "acc-001",
    date: "2025-01-27",
    description: "Uber ride to airport",
    merchant: "Uber Technologies",
    category: "transport",
    amount: -45.32,
    type: "debit",
    status: "completed",
  },
  {
    id: "txn-005",
    accountId: "acc-001",
    date: "2025-01-26",
    description: "Electric bill payment",
    merchant: "City Power & Light",
    category: "utilities",
    amount: -124.5,
    type: "debit",
    status: "completed",
  },
  {
    id: "txn-006",
    accountId: "acc-001",
    date: "2025-01-26",
    description: "Netflix subscription",
    merchant: "Netflix",
    category: "entertainment",
    amount: -15.99,
    type: "debit",
    status: "completed",
  },
  {
    id: "txn-007",
    accountId: "acc-004",
    date: "2025-01-25",
    description: "New laptop purchase",
    merchant: "Apple Store",
    category: "shopping",
    amount: -1299.0,
    type: "debit",
    status: "completed",
  },
  {
    id: "txn-008",
    accountId: "acc-001",
    date: "2025-01-25",
    description: "Doctor visit copay",
    merchant: "City Medical Center",
    category: "healthcare",
    amount: -35.0,
    type: "debit",
    status: "completed",
  },
  {
    id: "txn-009",
    accountId: "acc-001",
    date: "2025-01-24",
    description: "Transfer to savings",
    merchant: "Internal Transfer",
    category: "transfer",
    amount: -500.0,
    type: "transfer",
    status: "completed",
  },
  {
    id: "txn-010",
    accountId: "acc-002",
    date: "2025-01-24",
    description: "Transfer from checking",
    merchant: "Internal Transfer",
    category: "transfer",
    amount: 500.0,
    type: "transfer",
    status: "completed",
  },
  {
    id: "txn-011",
    accountId: "acc-001",
    date: "2025-01-23",
    description: "Coffee and pastry",
    merchant: "Starbucks",
    category: "dining",
    amount: -12.45,
    type: "debit",
    status: "completed",
  },
  {
    id: "txn-012",
    accountId: "acc-001",
    date: "2025-01-23",
    description: "Gas station fill-up",
    merchant: "Shell Gas Station",
    category: "transport",
    amount: -58.67,
    type: "debit",
    status: "completed",
  },
  {
    id: "txn-013",
    accountId: "acc-001",
    date: "2025-01-22",
    description: "Grocery essentials",
    merchant: "Trader Joe's",
    category: "groceries",
    amount: -89.34,
    type: "debit",
    status: "completed",
  },
  {
    id: "txn-014",
    accountId: "acc-001",
    date: "2025-01-22",
    description: "Movie tickets",
    merchant: "AMC Theatres",
    category: "entertainment",
    amount: -32.0,
    type: "debit",
    status: "completed",
  },
  {
    id: "txn-015",
    accountId: "acc-001",
    date: "2025-01-21",
    description: "Internet bill",
    merchant: "Comcast Xfinity",
    category: "utilities",
    amount: -89.99,
    type: "debit",
    status: "pending",
  },
  {
    id: "txn-016",
    accountId: "acc-004",
    date: "2025-01-21",
    description: "Online shopping",
    merchant: "Amazon",
    category: "shopping",
    amount: -156.78,
    type: "debit",
    status: "completed",
  },
  {
    id: "txn-017",
    accountId: "acc-001",
    date: "2025-01-20",
    description: "Pharmacy purchase",
    merchant: "CVS Pharmacy",
    category: "healthcare",
    amount: -24.56,
    type: "debit",
    status: "completed",
  },
  {
    id: "txn-018",
    accountId: "acc-001",
    date: "2025-01-20",
    description: "Lunch at work",
    merchant: "Chipotle",
    category: "dining",
    amount: -14.85,
    type: "debit",
    status: "completed",
  },
  {
    id: "txn-019",
    accountId: "acc-001",
    date: "2025-01-19",
    description: "Weekend groceries",
    merchant: "Costco",
    category: "groceries",
    amount: -234.56,
    type: "debit",
    status: "completed",
  },
  {
    id: "txn-020",
    accountId: "acc-001",
    date: "2025-01-19",
    description: "Spotify subscription",
    merchant: "Spotify",
    category: "entertainment",
    amount: -9.99,
    type: "debit",
    status: "completed",
  },
  {
    id: "txn-021",
    accountId: "acc-001",
    date: "2025-01-18",
    description: "Parking fee",
    merchant: "City Parking",
    category: "transport",
    amount: -15.0,
    type: "debit",
    status: "completed",
  },
  {
    id: "txn-022",
    accountId: "acc-001",
    date: "2025-01-18",
    description: "Phone bill",
    merchant: "Verizon",
    category: "utilities",
    amount: -85.0,
    type: "debit",
    status: "completed",
  },
  {
    id: "txn-023",
    accountId: "acc-004",
    date: "2025-01-17",
    description: "Clothing purchase",
    merchant: "Nordstrom",
    category: "shopping",
    amount: -189.0,
    type: "debit",
    status: "completed",
  },
  {
    id: "txn-024",
    accountId: "acc-001",
    date: "2025-01-17",
    description: "Date night dinner",
    merchant: "Per Se",
    category: "dining",
    amount: -245.0,
    type: "debit",
    status: "completed",
  },
  {
    id: "txn-025",
    accountId: "acc-001",
    date: "2025-01-16",
    description: "Gym membership",
    merchant: "Equinox",
    category: "healthcare",
    amount: -185.0,
    type: "debit",
    status: "completed",
  },
  {
    id: "txn-026",
    accountId: "acc-001",
    date: "2025-01-16",
    description: "Concert tickets",
    merchant: "Ticketmaster",
    category: "entertainment",
    amount: -150.0,
    type: "debit",
    status: "pending",
  },
  {
    id: "txn-027",
    accountId: "acc-001",
    date: "2025-01-15",
    description: "Freelance payment",
    merchant: "Client ABC",
    category: "income",
    amount: 1500.0,
    type: "credit",
    status: "completed",
  },
  {
    id: "txn-028",
    accountId: "acc-001",
    date: "2025-01-15",
    description: "Weekly groceries",
    merchant: "Safeway",
    category: "groceries",
    amount: -112.34,
    type: "debit",
    status: "completed",
  },
  {
    id: "txn-029",
    accountId: "acc-001",
    date: "2025-01-14",
    description: "Train pass",
    merchant: "Metro Transit",
    category: "transport",
    amount: -95.0,
    type: "debit",
    status: "completed",
  },
  {
    id: "txn-030",
    accountId: "acc-001",
    date: "2025-01-14",
    description: "Water bill",
    merchant: "City Water Dept",
    category: "utilities",
    amount: -45.67,
    type: "debit",
    status: "failed",
  },
];

export const categories: TransactionCategory[] = [
  "groceries",
  "dining",
  "transport",
  "utilities",
  "entertainment",
  "shopping",
  "healthcare",
  "income",
  "transfer",
];

export function getTransactionsByCategory(
  txns: Transaction[],
  category: TransactionCategory,
): Transaction[] {
  return txns.filter((txn) => txn.category === category);
}

export function getTransactionsByAccount(
  txns: Transaction[],
  accountId: string,
): Transaction[] {
  return txns.filter((txn) => txn.accountId === accountId);
}

export function getRecentTransactions(
  txns: Transaction[],
  limit: number = 10,
): Transaction[] {
  return [...txns]
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
    .slice(0, limit);
}
